### ISSUE TITLE
Initial planning

### ISSUE THREAD

**Issue by MitMaro** [MitMaro/code.review#1]
Features:
- Browse a git repository (or gist)
- View any text file in the repository (no initial support for binary files)
- Comment on any line/range in that file
- Comments are stored in git notes for the commits of the line/range
- Use git blame to get commit for line
- As a line/range comment is no longer in current version of file it disappears from view
  *\* Perhaps later we can show notes on old commits

Options:
- Branch support

**Comment by MitMaro** [comment]
@whymarrh Care to add or comment, I really want to start this?

**Comment by whymarrh** [comment]
> - Comments are stored in git notes for the commits of the line/range
> - Use `git blame` to get commit for line

I'm not sure how that would work, but I do like the idea of using Git as a data store. A few other ideas:
- I'd say just Gists
- Possibly use the gist URLs to generate site URLs
  
  That is, `https://gist.github.com/whymarrh/5ef3908f5b6728db2401` can be written as just `https://gist.github.com/5ef3908f5b6728db2401`, so I would imagine that `5ef3908f5b6728db2401` is some sort of identifier for the Gist that could be used

Branch support would be more in the realm of full-featured repositories.

**Comment by MitMaro** [comment]
I am fine with just gists to start, though I can think of a good use case for a repo wide review. A gist is just a git repository with revisions and multiple files, but no directories.

```
mitmaro /tmp (10 files) 
:) git clone https://gist.github.com/a30eb6896464a03092d7.git
Cloning into 'a30eb6896464a03092d7'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Checking connectivity... done.
mitmaro /tmp (11 files) 
:) cd a30eb6896464a03092d7/
(GIT) mitmaro /tmp/a30eb6896464a03092d7 (1 files)  (master) 
:) git log
commit 6f6af7e90aaa6ea7af744866f384a2d419b066d6
Author: Tim Oram <mitmaro@gmail.com>
Date:   Wed Mar 11 10:58:47 2015 -0700

commit e9157a08ca0b6f32fb52f5790d70b650e141e065
Author: Tim Oram <mitmaro@gmail.com>
Date:   Wed Mar 11 10:39:49 2015 -0700
(GIT) mitmaro /tmp/a30eb6896464a03092d7 (1 files)  (master) 
:) ls
Combine.js
```

**Comment by MitMaro** [comment]
How's this?

Features:
- View a gist
- View any text file in the gist
- Comment on any line/range in that file
- Comments are stored in git notes for the commits of the line/range
  - Notes are stored in a commit, we would have to define a format. An example:
    
    ```
    #1 ROOT 3-10: Tim Oram <tim@example.com>
    A note about the commit, that
    can support multiple lines.
    
    #2 REPLY #1: Whymarrh <whymarh@example.com>
    A reply to the above note
    ```
- Use git blame to get commit for line
  - We need a commit to store a note, git blame (or similar lower level tool) would tell you the commit
- As a line/range comment is no longer in current version of file it disappears from view
  - Perhaps later we can show notes on old commits

**Comment by MitMaro** [comment]
How would you feel about React on the client side and nodejs for the API. There is a nodegit project that GitHub seems to ~~use~~ sponsor: https://github.com/nodegit/nodegit

**Comment by MitMaro** [comment]
As per discussion Friday evening:
We will use JSON to store the comments for a commit.

Possible structure:

``` javascript

// perhaps instead of array use an object indexed by filename, though the index can be used as an id
var a = [
    {
        file: 'filename.js',
        // sorted by line number?
        comments: [
            // comment on single line
            {
                lines: '23',
                author: {
                    name: 'Tim',
                    email: 'tim@example.com'
                },
                // markdown?
                comment: 'comment text',
                replies: [
                    {
                        // same as parent comment
                    }
                ]
            },
            // multi line
            {
                lines: '45-60',
                author: { /* see above */},
                comment: 'comment',
                replies: [ /* see above */]
            }
        ]
    },
    {
        // repeat for every file with comment
    }
];
```

**Comment by whymarrh** [comment]
That format looks great. I would offer a few comments (no pun intended):
- Separate start line and end line (the same number for both representing a single line comment)
- `author` could be just a user identifier
- Calling the content either "content" or "text" vs "comment" might be less confusing/repetitive
- Index by filename (as per the comment on the first line above)

e.g.

``` json
{
    "filename.js": {
        "comments": [{
            "start_line": 2,
            "end_line": 5,
            "author": 42,
            "text": "foo bar baz",
            "replies": [{

            }]
        }]
    }
}
```

**Comment by whymarrh** [comment]
Addendum: possibly index by Git object name (hash)

**Comment by MitMaro** [comment]
Agree with everything and am fine with text. I also don't see an issue with going by object hash.

**Comment by MitMaro** [comment]
Shall we close, I think we have the initial planning done.
