### ISSUE TITLE
Package.json files

### ISSUE THREAD

**Issue by MitMaro** [MitMaro/code.review#10]
There are two pull request up now that are sharing a package.json. Should we split them into one for client, one for server and one for the global build?

**Comment by whymarrh** [comment]
Do we anticipate a global build?

**Comment by MitMaro** [comment]
Perhaps not a true global build but there should be something for CI (Travis?). We also need a global package.json file for the project as most tools look in the root of the project on GitHub.

**Comment by whymarrh** [comment]
It's probably easiest then to keep the one `package.json` file, continuing to have it be shared with both the client and API. How does that sound?

**Comment by MitMaro** [comment]
I am alright with that for the moment at least. Eventually I would like to see the two projects split.
